server:
  port: ${PETWALK_PORT:8002}

spring:
  application:
    name: walk-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:file:../../.env[.properties]

  # S3 비활성화 (pet-walk 모듈은 S3 사용 안 함)
  cloud:
    aws:
      s3:
        enabled: false
      region:
        static: ap-southeast-2  # S3 미사용이지만 자동설정 오류 방지용

  # MySQL Database Configuration
  datasource:
    url: ${PETWALK_DB_URL}
    username: ${PETWALK_DB_USERNAME}
    password: ${PETWALK_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

# Application Configuration
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  # Authentication Interceptor Configuration
  auth:
    interceptor:
      enabled: true

  # Kakao API Configuration
  kakao:
    api-key: ${KAKAO_API_KEY}

# Logging
logging:
  level:
    petwalk: ${LOG_LEVEL:DEBUG}
    com.myrealpet: ${LOG_LEVEL:DEBUG}