version: '3.8'

services:
  account:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: account
    container_name: myrealpet-account
    ports:
      - "8005:8005"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ACCOUNT_PORT=8005
      - ACCOUNT_DB_URL=jdbc:mysql://${DB_ENDPOINT}:3306/myrealpet_account?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      - ACCOUNT_DB_USERNAME=${DB_USERNAME}
      - ACCOUNT_DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - PORT=8005
    restart: unless-stopped
    networks:
      - myrealpet-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8005/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pet-walk:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: pet-walk
    container_name: myrealpet-petwalk
    ports:
      - "8002:8002"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PETWALK_PORT=8002
      - PETWALK_DB_URL=jdbc:mysql://${DB_ENDPOINT}:3306/myrealpet_walk?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      - PETWALK_DB_USERNAME=${DB_USERNAME}
      - PETWALK_DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - PORT=8002
    restart: unless-stopped
    networks:
      - myrealpet-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8002/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  sns:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sns
    container_name: myrealpet-sns
    ports:
      - "8007:8007"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SNS_PORT=8007
      - SNS_DB_URL=jdbc:mysql://${DB_ENDPOINT}:3306/myrealpet_sns?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      - SNS_DB_USERNAME=${DB_USERNAME}
      - SNS_DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - PORT=8007
    restart: unless-stopped
    networks:
      - myrealpet-network
    depends_on:
      - account
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8007/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: myrealpet-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - myrealpet-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  myrealpet-network:
    driver: bridge
