version: '3.8'

services:
  account:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: account
    container_name: myrealpet-account
    ports:
      - "8005:8005"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ACCOUNT_PORT=8005
      - ACCOUNT_DB_URL=jdbc:mysql://${DB_ENDPOINT}:3306/myrealpet_account?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      - ACCOUNT_DB_USERNAME=${DB_USERNAME}
      - ACCOUNT_DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - PORT=8005
    restart: unless-stopped
    networks:
      - myrealpet-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8005/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pet-walk:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: pet-walk
    container_name: myrealpet-petwalk
    ports:
      - "8002:8002"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PETWALK_PORT=8002
      - PETWALK_DB_URL=jdbc:mysql://${DB_ENDPOINT}:3306/myrealpet_petwalk?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      - PETWALK_DB_USERNAME=${DB_USERNAME}
      - PETWALK_DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - PORT=8002
    restart: unless-stopped
    networks:
      - myrealpet-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8002/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  myrealpet-network:
    driver: bridge
