server:
  port: ${SNS_PORT:8007}

spring:
  application:
    name: sns-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:file:../../.env[.properties]

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # MySQL Database Configuration
  datasource:
    url: ${SNS_DB_URL:jdbc:mysql://localhost:3306/myrealpet_sns?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC}
    username: ${SNS_DB_USERNAME:myrealpet}
    password: ${SNS_DB_PASSWORD:roota123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  # AWS S3 Configuration
  cloud:
    aws:
      credentials:
        access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
        secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        enabled: true
        bucket: myrealpet
      stack:
        auto: false

# Application Configuration
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  # Authentication Interceptor Configuration
  auth:
    interceptor:
      enabled: true

# Logging
logging:
  level:
    sns: ${LOG_LEVEL:DEBUG}
    com.myrealpet: ${LOG_LEVEL:DEBUG}
    org.springframework: INFO
