name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (Account API)
        run: ./gradlew :account:api:bootJar

      - name: Build with Gradle (Pet-Walk API)
        run: ./gradlew :pet-walk:api:bootJar

      - name: Deploy Account API to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "account/api/build/libs/*.jar"
          target: "/home/ubuntu/app"
          strip_components: 3

      - name: Deploy Pet-Walk API to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "pet-walk/api/build/libs/*.jar"
          target: "/home/ubuntu/app"
          strip_components: 3

      - name: Copy deployment script to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "deploy.sh"
          target: "/home/ubuntu/app"

      - name: Execute deployment script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 30s
          script: |
            chmod +x /home/ubuntu/app/deploy.sh

            # Set environment variables and run deployment script in background
            # Using setsid to completely detach from SSH session
            export ACCOUNT_DB_URL="jdbc:mysql://${{ secrets.DB_ENDPOINT }}:3306/myrealpet?serverTimezone=Asia/Seoul"
            export ACCOUNT_DB_USERNAME="admin"
            export ACCOUNT_DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export REDIS_HOST="localhost"
            export REDIS_PORT="6379"
            export REDIS_PASSWORD=""
            export CORS_ALLOWED_ORIGINS="*"
            export PET_WALK_DB_URL="jdbc:mysql://${{ secrets.DB_ENDPOINT }}:3306/myrealpet?serverTimezone=Asia/Seoul"
            export PET_WALK_DB_USERNAME="admin"
            export PET_WALK_DB_PASSWORD="${{ secrets.DB_PASSWORD }}"

            # Run deployment script in background, completely detached from SSH
            setsid bash /home/ubuntu/app/deploy.sh > /dev/null 2>&1 < /dev/null &

            echo "Deployment script started in background"
            echo "Check logs at: /home/ubuntu/app/logs/deploy.log"
