name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (Account API)
        run: ./gradlew :account:api:bootJar

      - name: Build with Gradle (Pet-Walk API)
        run: ./gradlew :pet-walk:api:bootJar

      - name: Deploy Account API to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "account/api/build/libs/*.jar"
          target: "/home/ubuntu/app"
          strip_components: 3

      - name: Deploy Pet-Walk API to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "pet-walk/api/build/libs/*.jar"
          target: "/home/ubuntu/app"
          strip_components: 3

      - name: Execute deployment script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 10m
          script: |
            # Stop existing apps
            pkill -f 'account.*jar' || true
            pkill -f 'pet-walk.*jar' || true

            # Wait for ports to be released
            sleep 5

            # Start Account API
            cd /home/ubuntu/app
            nohup java -jar \
              -Dspring.profiles.active=prod \
              -DACCOUNT_DB_URL=jdbc:mysql://${{ secrets.DB_ENDPOINT }}:3306/myrealpet?serverTimezone=Asia/Seoul \
              -DACCOUNT_DB_USERNAME=admin \
              -DACCOUNT_DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -DREDIS_HOST=localhost \
              -DREDIS_PORT=6379 \
              -DREDIS_PASSWORD= \
              -DCORS_ALLOWED_ORIGINS=* \
              account-api*.jar > account.log 2>&1 &

            # Detach process from shell
            disown

            # Start Pet-Walk API
            nohup java -jar \
              -Dspring.profiles.active=prod \
              -DPET_WALK_DB_URL=jdbc:mysql://${{ secrets.DB_ENDPOINT }}:3306/myrealpet?serverTimezone=Asia/Seoul \
              -DPET_WALK_DB_USERNAME=admin \
              -DPET_WALK_DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              pet-walk-api*.jar > pet-walk.log 2>&1 &

            # Detach process from shell
            disown

            # Wait a moment for processes to start
            sleep 2

            echo "Deployment completed!"
            exit 0
